// Playground Slice A — asset URL manifest. Pure data, no React.
//
// This manifest IS the contract for the /cats/playground/* art set:
// the sequence tables (playgroundSequences.ts) and the diorama page
// validate against these constants, NOT against the disk. The PNGs
// are still being generated by the image pipeline as of this slice.
//
// TODO(playground-export): once the asset-export step lands, add an
// on-disk existence test that walks every URL below against
// client/public/cats/playground/ (same spirit as CAT_ANIM_MANIFEST's
// checked-in set). Do NOT add it before the export ships — it would
// hard-fail the suite on art that is intentionally not here yet.

export const PLAYGROUND_CAT_IDS = ['panther', 'mushu', 'coco'] as const
export type PlaygroundCatId = (typeof PLAYGROUND_CAT_IDS)[number]

const BASE = '/cats/playground'

export const PLAYGROUND_FURNITURE_NAMES = [
  'cat_tree_deluxe',
  'wall_shelf_set',
  'tunnel',
  'hammock',
  'window_perch',
  'scratching_post',
  'rug',
  'food_bowl',
  'water_bowl',
  'litter_box',
  'plant',
  'bird_feeder',
] as const
export type PlaygroundFurnitureName = (typeof PLAYGROUND_FURNITURE_NAMES)[number]

export const PLAYGROUND_TOY_NAMES = [
  'yarn_idle',
  'yarn_roll_a',
  'yarn_roll_b',
  'feather_wand',
  'treat',
  'mouse_toy',
] as const
export type PlaygroundToyName = (typeof PLAYGROUND_TOY_NAMES)[number]

export const PLAYGROUND_AMBIENT_NAMES = [
  'butterfly_a',
  'butterfly_b',
  'bird_a',
  'bird_b',
] as const
export type PlaygroundAmbientName = (typeof PLAYGROUND_AMBIENT_NAMES)[number]

/** Playground-only cat frames (per cat, under /{catId}/). The shared
    ambient frames (seated, walk_*, …) stay in catAnimSequences'
    CAT_ANIM_MANIFEST under /cats/anim/. */
export const PLAYGROUND_CAT_FRAME_NAMES = [
  'bat_a',
  'bat_b',
  'eat_a',
  'eat_b',
  'purr',
] as const
export type PlaygroundCatFrameName = (typeof PLAYGROUND_CAT_FRAME_NAMES)[number]

function urlMap<N extends string>(dir: string, names: readonly N[]): Record<N, string> {
  return Object.fromEntries(
    names.map((name) => [name, `${BASE}/${dir}/${name}.png`]),
  ) as Record<N, string>
}

export const PLAYGROUND_FURNITURE_URLS: Record<PlaygroundFurnitureName, string> =
  urlMap('furniture', PLAYGROUND_FURNITURE_NAMES)

export const PLAYGROUND_TOY_URLS: Record<PlaygroundToyName, string> =
  urlMap('toys', PLAYGROUND_TOY_NAMES)

export const PLAYGROUND_AMBIENT_URLS: Record<PlaygroundAmbientName, string> =
  urlMap('ambient', PLAYGROUND_AMBIENT_NAMES)

export const PLAYGROUND_CAT_FRAME_URLS: Record<
  PlaygroundCatId,
  Record<PlaygroundCatFrameName, string>
> = {
  panther: urlMap('panther', PLAYGROUND_CAT_FRAME_NAMES),
  mushu: urlMap('mushu', PLAYGROUND_CAT_FRAME_NAMES),
  coco: urlMap('coco', PLAYGROUND_CAT_FRAME_NAMES),
}

export function playgroundCatFrameUrl(
  catId: PlaygroundCatId,
  frame: PlaygroundCatFrameName,
): string {
  return PLAYGROUND_CAT_FRAME_URLS[catId][frame]
}

// === Preload waves ===========================================================
// Wave 1 is the static diorama (furniture only) — the page gates its
// first paint on this set so the scene never pops in piecemeal.
// Wave 2 is everything that moves (toys, ambient critters, per-cat
// playground frames) — warmed in the background after the scene is up.

export const PLAYGROUND_PRELOAD_WAVE_1: readonly string[] =
  PLAYGROUND_FURNITURE_NAMES.map((name) => PLAYGROUND_FURNITURE_URLS[name])

export const PLAYGROUND_PRELOAD_WAVE_2: readonly string[] = [
  ...PLAYGROUND_TOY_NAMES.map((name) => PLAYGROUND_TOY_URLS[name]),
  ...PLAYGROUND_AMBIENT_NAMES.map((name) => PLAYGROUND_AMBIENT_URLS[name]),
  ...PLAYGROUND_CAT_IDS.flatMap((catId) =>
    PLAYGROUND_CAT_FRAME_NAMES.map((frame) => PLAYGROUND_CAT_FRAME_URLS[catId][frame]),
  ),
]
