// Playground Slice A — asset URL manifest. Pure data, no React.
//
// This manifest IS the contract for the /cats/playground/* art set:
// the sequence tables (playgroundSequences.ts) and the diorama page
// validate against these constants, NOT against the disk. The PNGs
// are still being generated by the image pipeline as of this slice.
//
// TODO(playground-export): once the asset-export step lands, add an
// on-disk existence test that walks every URL below against
// client/public/cats/playground/ (same spirit as CAT_ANIM_MANIFEST's
// checked-in set). Do NOT add it before the export ships — it would
// hard-fail the suite on art that is intentionally not here yet.

export const PLAYGROUND_CAT_IDS = ['panther', 'mushu', 'coco'] as const
export type PlaygroundCatId = (typeof PLAYGROUND_CAT_IDS)[number]

const BASE = '/cats/playground'

export const PLAYGROUND_FURNITURE_NAMES = [
  'cat_tree_deluxe',
  'wall_shelf_set',
  'tunnel',
  'hammock',
  'window_perch',
  'scratching_post',
  'rug',
  'food_bowl',
  'water_bowl',
  'litter_box',
  'plant',
  'bird_feeder',
] as const
export type PlaygroundFurnitureName = (typeof PLAYGROUND_FURNITURE_NAMES)[number]

export const PLAYGROUND_TOY_NAMES = [
  'yarn_idle',
  'yarn_roll_a',
  'yarn_roll_b',
  'feather_wand',
  'treat',
  'mouse_toy',
] as const
export type PlaygroundToyName = (typeof PLAYGROUND_TOY_NAMES)[number]

export const PLAYGROUND_AMBIENT_NAMES = [
  'butterfly_a',
  'butterfly_b',
  'bird_a',
  'bird_b',
] as const
export type PlaygroundAmbientName = (typeof PLAYGROUND_AMBIENT_NAMES)[number]

/** Playground-only cat frames EVERY cat has on disk (per cat, under
    /{catId}/). The shared ambient frames (seated, walk_*, …) stay in
    catAnimSequences' CAT_ANIM_MANIFEST under /cats/anim/. */
const SHARED_PLAYGROUND_CAT_FRAMES = [
  'bat_a',
  'bat_b',
  'eat_a',
  'eat_b',
  'purr',
  // Interaction wave 2026-07-11: scratch/climb ride 160-tall canvases
  // (standing stretch / vertical cling); the rest stay 128-tall.
  'scratch_a',
  'scratch_b',
  'climb_a',
  'climb_b',
  'drink_a',
  'drink_b',
  'hammock_lie',
  'window_watch',
  // Tween wave 2 2026-07-11: generated a↔b midpoints for the sparse
  // playground pairs. scratch_ab inherits its pair's 160-tall canvas;
  // the rest are 128-tall.
  'scratch_ab',
  'eat_ab',
  'bat_ab',
  // Frames-30 wave 2c (2026-07-12): bout-variant keys + midpoints, all
  // three cats. scrhi_* ride the 160-tall scratch canvas; the rest are
  // 128-tall. sniff_* are dual-homed (also in /cats/anim/) — the
  // playground copies keep the URL router total.
  'scrhi_a',
  'scrhi_ab',
  'scrhi_b',
  'batl_a',
  'batr_a',
  'eatlift_a',
  'eatlift_ab',
  'eatlift_b',
  'drinkup_a',
  'drinkup_b',
  'pawdip_a',
  'pawdip_ab',
  'pawdip_b',
  'sniff_a',
  'sniff_ab',
  'sniff_b',
  // Frames-30 wave 4 (2026-07-12): habitat transitions — climb mount/
  // dismount arcs, hammock settle-in circling, window chatter head-
  // tracking (back views). mount_*/dismount_* ride the 160-tall climb
  // canvas group where drawn tall; the rest are 128-tall.
  'mount_a',
  'mount_ab',
  'mount_b',
  'dismount_a',
  'dismount_ab',
  'dismount_b',
  'hamset_a',
  'hamset_ab',
  'hamset_b',
  'chatter_a',
  'chatter_ab',
  'chatter_b',
  // Wave-5 slices 3-4 (2026-07-12/13): bout second-level midpoints, the
  // window-life pack (all back views), paw-over-paw climbing, and the
  // crunch chew. scrhi_n*/mount_n*/dismount_n* ride their pairs' canvas
  // groups; everything else is 128-tall.
  'scratch_n1', 'scratch_n2',
  'scrhi_n1', 'scrhi_n2',
  'bat_n1', 'bat_n2',
  'eat_n1', 'eat_n2', 'eatlift_n1', 'crunch_a',
  'drink_n1', 'pawdip_n1',
  'mount_n1', 'mount_n2', 'dismount_n1', 'dismount_n2', 'climb_n1',
  'hamset_n1', 'chatter_n1', 'chatter_n2',
  'wtail_a', 'wtail_ab', 'wtail_b',
  'wear_a',
  'wpan_a', 'wpan_ab', 'wpan_b',
  'wcrouch_a',
  'wsill_a', 'wsill_ab', 'wsill_b',
  'wduck_a', 'wlie_a', 'wstretch_a',
  'knead_a', 'knead_ab', 'knead_b',
  'pawover_a', 'pawover_ab', 'pawover_b',
] as const

/** Full frame-name union (URL routing + typing). Two tween midpoints
    are per-cat — same pattern as blink/sleep_b2 in CAT_ANIM_MANIFEST:
    the re-rolls for coco/drink_ab, mushu/climb_ab and panther/climb_ab
    came out deformed twice and were permanently dropped (2026-07-11),
    so climb_ab is Coco-only and drink_ab is Panther+Mushu-only. */
export const PLAYGROUND_CAT_FRAME_NAMES = [
  ...SHARED_PLAYGROUND_CAT_FRAMES,
  'climb_ab',
  'drink_ab',
] as const
export type PlaygroundCatFrameName = (typeof PLAYGROUND_CAT_FRAME_NAMES)[number]

/** What is actually on disk per cat. Sequences must only use frames
    from their cat's manifest (pinned by playgroundSequences.test). */
export const PLAYGROUND_CAT_FRAME_MANIFEST: Record<
  PlaygroundCatId,
  readonly PlaygroundCatFrameName[]
> = {
  panther: [...SHARED_PLAYGROUND_CAT_FRAMES, 'drink_ab'],
  mushu: [...SHARED_PLAYGROUND_CAT_FRAMES, 'drink_ab'],
  coco: [...SHARED_PLAYGROUND_CAT_FRAMES, 'climb_ab'],
}

function urlMap<N extends string>(dir: string, names: readonly N[]): Record<N, string> {
  return Object.fromEntries(
    names.map((name) => [name, `${BASE}/${dir}/${name}.png`]),
  ) as Record<N, string>
}

export const PLAYGROUND_FURNITURE_URLS: Record<PlaygroundFurnitureName, string> =
  urlMap('furniture', PLAYGROUND_FURNITURE_NAMES)

export const PLAYGROUND_TOY_URLS: Record<PlaygroundToyName, string> =
  urlMap('toys', PLAYGROUND_TOY_NAMES)

export const PLAYGROUND_AMBIENT_URLS: Record<PlaygroundAmbientName, string> =
  urlMap('ambient', PLAYGROUND_AMBIENT_NAMES)

/** Per-cat URL map, manifest-driven — a cat only lists URLs for
    frames it actually has (hence Partial for the per-cat midpoints). */
export const PLAYGROUND_CAT_FRAME_URLS: Record<
  PlaygroundCatId,
  Readonly<Partial<Record<PlaygroundCatFrameName, string>>>
> = {
  panther: urlMap('panther', PLAYGROUND_CAT_FRAME_MANIFEST.panther),
  mushu: urlMap('mushu', PLAYGROUND_CAT_FRAME_MANIFEST.mushu),
  coco: urlMap('coco', PLAYGROUND_CAT_FRAME_MANIFEST.coco),
}

export function playgroundCatFrameUrl(
  catId: PlaygroundCatId,
  frame: PlaygroundCatFrameName,
): string {
  // Constructed (not manifest-indexed) so the signature stays total;
  // sequences are pinned to only use frames in their cat's manifest,
  // and PlaygroundCat has a 404 fallback besides.
  return `${BASE}/${catId}/${frame}.png`
}

// === Preload waves ===========================================================
// Wave 1 is the static diorama (furniture only) — the page gates its
// first paint on this set so the scene never pops in piecemeal.
// Wave 2 is everything that moves (toys, ambient critters, per-cat
// playground frames) — warmed in the background after the scene is up.

export const PLAYGROUND_PRELOAD_WAVE_1: readonly string[] =
  PLAYGROUND_FURNITURE_NAMES.map((name) => PLAYGROUND_FURNITURE_URLS[name])

export const PLAYGROUND_PRELOAD_WAVE_2: readonly string[] = [
  ...PLAYGROUND_TOY_NAMES.map((name) => PLAYGROUND_TOY_URLS[name]),
  ...PLAYGROUND_AMBIENT_NAMES.map((name) => PLAYGROUND_AMBIENT_URLS[name]),
  ...PLAYGROUND_CAT_IDS.flatMap((catId) =>
    PLAYGROUND_CAT_FRAME_MANIFEST[catId].map((frame) => playgroundCatFrameUrl(catId, frame)),
  ),
]
