#!/usr/bin/env python3
"""Generate dependency-free worker contract helpers from the canonical schema."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "contracts/internal-worker.schema.json"
PY_OUT = ROOT / "detection/generated_wire_contract.py"
TS_OUT = ROOT / "client/src/generated/internalWorkerContract.ts"


def render(schema):
    defs = schema["$defs"]
    event = defs["DetectionEvent"]["properties"]
    heartbeat = defs["Heartbeat"]["properties"]
    py = """# Generated by scripts/generate-contracts.py; do not edit.\n# Python 3.6 compatible.\nEVENT_FIELDS = %r\nHEARTBEAT_FIELDS = %r\n""" % (
        tuple(sorted(event)), tuple(sorted(heartbeat)),
    )
    optional = set(event) - set(defs["DetectionEvent"]["required"])
    lines = [
        "// Generated by scripts/generate-contracts.py; do not edit.",
        "export interface WorkerBox { x: number; y: number; w: number; h: number; label: string; score: number }",
        "export interface WorkerDetectionEvent {",
    ]
    ts_types = {"label": "string", "score": "number", "boxes": "WorkerBox[]", "camera_id": "string", "continuation": "boolean", "thumb_url": "string | null", "clip_url": "string | null", "id": "string | null", "person_name": "string | null", "person_names": "string[] | null", "source": "'vision'", "rule_id": "string | null", "rule_name": "string | null", "correlation_id": "string | null", "related_event_id": "string | null", "visit_id": "string | null", "start_ts": "number | null", "end_ts": "number | null", "package_state": "'delivered' | 'collected' | null"}
    for name in event:
        lines.append("  %s%s: %s;" % (name, "?" if name in optional else "", ts_types[name]))
    lines += ["}", "export interface WorkerHeartbeat {"]
    for name, prop in heartbeat.items():
        typ = "string[]" if name == "face_recog_names" else ("string" if prop["type"] == "string" else "number")
        lines.append("  %s?: %s;" % (name, typ))
    lines += ["}", ""]
    return py, "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    expected = render(json.loads(SCHEMA.read_text()))
    stale = [path for path, body in zip((PY_OUT, TS_OUT), expected) if not path.exists() or path.read_text() != body]
    if args.check:
        if stale:
            parser.error("stale generated contracts: " + ", ".join(str(p.relative_to(ROOT)) for p in stale))
        return
    for path, body in zip((PY_OUT, TS_OUT), expected):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)


if __name__ == "__main__":
    main()
